### ISSUE TITLE
Use System R

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_stats#68]
Can we use the system R rather than building our own?

**Comment by snim2** [comment]
Working travis config from @smarr 

```yml
language: python

matrix:
  include:
    # - python: "2.7"
    #   os: linux
    #   sudo: false
    #   addons:
    #     apt:
    #       packages:
    #         - build-essential
    #         - r-base
    #         - gfortran
    - language: generic
      os: osx
      before_install: |
        brew cask uninstall oclint  # a travis issue
        brew update > /dev/null
        brew install gcc zlib
        export CFLAGS="-I$(xcrun --show-sdk-path)/usr/include"
script:
 - ./build.sh
```
